- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-n01603642
    - profile-n01603642
    - user-n01603642
    - webserver-n01603642

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"

